#!/usr/bin/env node
// Regenerates system/videofx.default from the settings list in src/config.js,
// so the file documents every key. Run after adding a setting:
//   node tools/gen-default.mjs > system/videofx.default

import { SETTINGS, resolveSettings } from "../src/config.js";

const ctx = { home: "/home/pi", deviceName: "VideoFX-XXXX", hostName: "videofx-xxxx" };
const defaults = resolveSettings({ ctx }).values;
const show = (v, key) => (key === "webHosts" ? v.join(" ") : Array.isArray(v) ? JSON.stringify(v) : typeof v === "object" && v !== null ? JSON.stringify(v) : v === null ? "" : String(v));

const out = [
  "# /etc/default/videofx - settings for videofx-player.service (generated by tools/gen-default.mjs).",
  "#",
  "# Almost everything here can also be changed on the web page (Settings), which",
  "# saves to /var/lib/videofx/settings.json. A value set on the web page WINS over",
  "# this file; the page's Reset goes back to this file, then to the default.",
  "# Precedence: web page > this file > built-in default. Lines are commented out,",
  "# so the defaults apply until you set them.",
  "#",
  "# systemd reads this file, not a shell. Put a value that contains quotes (the",
  "# JSON ones) in single quotes, as the examples do: quotes inside an unquoted",
  "# value are dropped, and the setting then falls back to its default.",
  "#",
  "# After editing: sudo systemctl restart videofx-player",
  "# Root-only (mode 600) because it can hold the web page password.",
  "",
];
let group = null;
for (const s of SETTINGS) {
  if (!s.env) continue;
  if (s.group !== group) {
    group = s.group;
    out.push("", group === "Fixed" ? "# --- File only (needs root, or would let the page point the service anywhere)" : `# --- ${group}`);
    if (group === "Fixed") {
      out.push(
        "# The relay and IR pins are also in /boot/firmware/config.txt (the relay's",
        "# boot level, and the IR overlays), written once by setup.sh with the",
        "# defaults. Change them there too, or the new pins won't work.",
      );
    }
  }
  const env = [s.env].flat().at(-1);
  out.push(`# ${s.label}${s.apply === "play" ? " (applies on the next play)" : s.apply === "restart" ? " (needs a service restart)" : ""}${s.help ? `. ${s.help}` : ""}`);
  const value = show(defaults[s.key], s.key);
  out.push(`#${env}=${/["]/.test(value) ? `'${value}'` : value}`);
}
console.log(out.join("\n"));
